// Builds a standalone, printable HTML report for an AI Visibility Score audit.
import { buildScoreBadgeSvg, bandColor } from "./score-badge";

export type ReportAudit = {
  business: string;
  overall: number;
  subscores: Array<{ label: string; score: number; note: string }>;
  strengths: string[];
  recommendations: string[];
  gbmStandalone?: string[];
  gbmKnowledgeGraph?: string[];
  summary: string;
  sources: string[];
};

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export function slugify(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export function buildAuditReportHtml(audit: ReportAudit): string {
  const color = bandColor(audit.overall);
  const badge = buildScoreBadgeSvg(audit.overall, 300);
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const list = (items: string[]) =>
    items.map((i) => `<li>${esc(i)}</li>`).join("");

  const subs = audit.subscores
    .map(
      (s) => `<div class="sub">
      <div class="subhead"><span>${esc(s.label)}</span><b>${s.score}/100</b></div>
      <div class="bar"><i style="width:${s.score}%"></i></div>
      ${s.note ? `<p>${esc(s.note)}</p>` : ""}
    </div>`,
    )
    .join("");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<title>${esc(audit.business)} — AI Visibility Score Audit</title>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<style>
  :root { --navy:#0B1E3F; --gold:#E8B54B; --band:${color}; }
  * { box-sizing:border-box; }
  body { margin:0; font-family:Helvetica,Arial,sans-serif; color:#111; background:#f5f6f8; }
  .page { max-width:820px; margin:0 auto; background:#fff; padding:48px; }
  header { display:flex; gap:28px; align-items:center; border-bottom:4px solid var(--gold); padding-bottom:24px; }
  header svg { flex:0 0 auto; }
  h1 { font-size:26px; margin:0 0 6px; color:var(--navy); }
  .meta { font-size:13px; color:#666; }
  h2 { font-size:15px; letter-spacing:1.5px; text-transform:uppercase; color:var(--navy); margin:34px 0 12px; }
  p { line-height:1.6; font-size:14px; }
  .subs { display:grid; grid-template-columns:1fr 1fr; gap:14px; }
  .sub { border:1px solid #e3e5ea; border-radius:8px; padding:12px; }
  .subhead { display:flex; justify-content:space-between; font-size:13px; font-weight:bold; color:var(--navy); }
  .bar { height:6px; border-radius:6px; background:#e8eaee; margin:8px 0; overflow:hidden; }
  .bar i { display:block; height:6px; background:var(--band); }
  .sub p { margin:0; font-size:12px; color:#555; line-height:1.5; }
  ul { padding-left:20px; } li { font-size:14px; line-height:1.6; margin-bottom:6px; }
  .sources li { font-size:12px; word-break:break-all; }
  .contact-card { margin-top:40px; border:2px solid var(--navy); border-radius:12px; padding:24px; background:#f8fafd; text-align:center; }
  .contact-card h2 { margin:0 0 8px; border:none; }
  .contact-name { font-size:20px; font-weight:bold; color:var(--navy); margin:0; }
  .contact-role { font-size:14px; color:#444; margin:4px 0 0; }
  .contact-links { font-size:15px; margin:12px 0 0; }
  .contact-links a { color:var(--navy); font-weight:bold; text-decoration:none; }
  footer { margin-top:40px; border-top:1px solid #e3e5ea; padding-top:14px; font-size:12px; color:#666; }
  @media print { body { background:#fff; } .page { padding:24px; max-width:none; } }
</style></head>
<body><div class="page">
  <header>
    ${badge}
    <div>
      <h1>${esc(audit.business)}</h1>
      <div class="meta">AI Visibility Score Audit &middot; ${date}<br/>audited by www.GetBizMusic.com</div>
    </div>
  </header>

  ${audit.summary ? `<h2>Summary</h2><p>${esc(audit.summary)}</p>` : ""}

  ${audit.subscores.length ? `<h2>Score breakdown</h2><div class="subs">${subs}</div>` : ""}

  ${audit.strengths.length ? `<h2>Strengths</h2><ul>${list(audit.strengths)}</ul>` : ""}

  ${audit.recommendations.length ? `<h2>Recommendations</h2><ul>${list(audit.recommendations)}</ul>` : ""}

  ${
    audit.sources.length
      ? `<h2>Sources reviewed</h2><ul class="sources">${audit.sources
          .map((u) => `<li><a href="${esc(u)}">${esc(u)}</a></li>`)
          .join("")}</ul>`
      : ""
  }

  <div class="contact-card">
    <h2>Contact</h2>
    <p class="contact-name">Ralph T. Posadas</p>
    <p class="contact-role">GetBizMusic Business Alliance</p>
    <p class="contact-role">To activate your membership:</p>
    <p class="contact-links">
      <a href="mailto:ralph@getbizmusic.com">ralph@getbizmusic.com</a><br/>
      Text/SMS (619) 707-0467
    </p>
  </div>

  <footer>Report generated by GetBizMusic &middot; www.GetBizMusic.com &middot; Open this file and use your browser&rsquo;s Print &rarr; Save as PDF to share a PDF copy.</footer>
</div></body></html>`;
}
