export const INDUSTRIES = [
  { value: "accounting_tax", label: "Accountant / Tax Services" },
  { value: "agriculture", label: "Agriculture / Farming" },
  { value: "auto", label: "Auto / Repair" },
  { value: "auto_body", label: "Auto Body / Collision" },
  { value: "auto_insurance", label: "Auto Insurance Agent" },
  { value: "auto_repair", label: "Auto Repair" },
  { value: "bakery", label: "Bakery" },
  { value: "bar_nightlife", label: "Bar / Nightlife" },
  { value: "barbershop", label: "Barbershop" },
  { value: "boutique_apparel", label: "Boutique / Apparel" },
  { value: "business_consulting", label: "Business Consulting" },
  { value: "business_opportunities", label: "Business Opportunities" },
  { value: "cafe_coffee", label: "Café / Coffee Shop" },
  { value: "auto_dealer", label: "Car Dealer" },
  { value: "car_wash", label: "Car Wash / Detailing" },
  { value: "catering", label: "Catering" },
  { value: "childcare_daycare", label: "Childcare / Daycare" },
  { value: "chiropractic", label: "Chiropractic" },
  { value: "church", label: "Church" },
  { value: "cleaning", label: "Cleaning Services" },
  { value: "community_org", label: "Community Organization" },
  { value: "community_event", label: "FREE Community Event" },
  { value: "convenience_store", label: "Convenience Store" },
  { value: "dance_school", label: "Dance School" },
  { value: "delivery_courier", label: "Delivery / Courier" },
  { value: "dental", label: "Dental" },
  { value: "dj_entertainment", label: "DJ / Entertainment" },
  { value: "dog_training", label: "Dog Training" },
  { value: "electrical", label: "Electrical" },
  { value: "esthetician", label: "Esthetician / Skincare" },
  { value: "event_planner", label: "Event Planner" },
  { value: "farmers_market", label: "Farmers Market" },
  { value: "financial_advisor", label: "Financial Advisor" },
  { value: "fitness_gym", label: "Fitness / Gym" },
  { value: "flooring", label: "Flooring" },
  { value: "florist", label: "Florist" },
  { value: "food_truck", label: "Food Truck" },
  { value: "franchise_opportunity", label: "Franchise Opportunity" },
  { value: "funeral_services", label: "Funeral Services" },
  { value: "gift_shop", label: "Gift Shop" },
  { value: "grocery", label: "Grocery / Market" },
  { value: "salon_hair", label: "Hair Salon" },
  { value: "handyman", label: "Handyman" },
  { value: "health_insurance", label: "Health Insurance Agent" },
  { value: "healthcare_general", label: "Healthcare (General)" },
  { value: "healthcare", label: "Healthcare / Dental" },
  { value: "services", label: "Home Services" },
  { value: "home_services_general", label: "Home Services (General)" },
  { value: "hotel_lodging", label: "Hotel / Lodging" },
  { value: "hvac", label: "HVAC / Heating & Cooling" },
  { value: "insurance_general", label: "Insurance (General)" },
  { value: "jewelry", label: "Jewelry" },
  { value: "landscaping_lawn", label: "Landscaping / Lawn Care" },
  { value: "lash_brow", label: "Lash / Brow Studio" },
  { value: "legal", label: "Lawyer / Legal" },
  { value: "life_insurance", label: "Life Insurance Agent" },
  { value: "liquor_store", label: "Liquor Store" },
  { value: "locksmith", label: "Locksmith" },
  { value: "marketing_agency", label: "Marketing / Advertising Agency" },
  { value: "martial_arts", label: "Martial Arts" },
  { value: "medical_spa", label: "Medical Spa" },
  { value: "mental_health_counseling", label: "Mental Health / Counseling" },
  { value: "ministry", label: "Ministry" },
  { value: "mortgage_lending", label: "Mortgage / Lending" },
  { value: "motorcycle_powersports", label: "Motorcycle / Powersports" },
  { value: "moving_storage", label: "Moving / Storage" },
  { value: "music_lessons", label: "Music Lessons" },
  { value: "nail_salon", label: "Nail Salon" },
  { value: "nonprofit", label: "Nonprofit" },
  { value: "notary", label: "Notary" },
  { value: "nutrition", label: "Nutrition / Wellness" },
  { value: "optometry", label: "Optometry / Eye Care" },
  { value: "other", label: "Other" },
  { value: "painting", label: "Painting" },
  { value: "party_rentals", label: "Party Rentals" },
  { value: "personal_trainer", label: "Personal Trainer" },
  { value: "pest_control", label: "Pest Control" },
  { value: "pet_boarding", label: "Pet Boarding / Daycare" },
  { value: "pet_grooming", label: "Pet Grooming" },
  { value: "pharmacy", label: "Pharmacy" },
  { value: "photographer", label: "Photographer" },
  { value: "physical_therapy", label: "Physical Therapy" },
  { value: "plumbing", label: "Plumbing" },
  { value: "pool_spa", label: "Pool / Spa Services" },
  { value: "printing_signs", label: "Printing / Signs" },
  { value: "private_school", label: "Private School" },
  { value: "property_management", label: "Property Management" },
  { value: "realestate", label: "Real Estate" },
  { value: "real_estate_agent", label: "Real Estate Agent" },
  { value: "real_estate_broker", label: "Real Estate Broker" },
  { value: "religious_services", label: "Religious Services" },
  { value: "restaurant", label: "Restaurant / Food" },
  { value: "retail", label: "Retail / Shopping" },
  { value: "roofing", label: "Roofing" },
  { value: "rv_boat", label: "RV / Boat" },
  { value: "salon", label: "Salon / Beauty" },
  { value: "security_services", label: "Security Services" },
  { value: "solar", label: "Solar" },
  { value: "spa_massage", label: "Spa / Massage" },
  { value: "staffing_recruiting", label: "Staffing / Recruiting" },
  { value: "tattoo_piercing", label: "Tattoo / Piercing" },
  { value: "thrift_secondhand", label: "Thrift / Secondhand" },
  { value: "tires_wheels", label: "Tires / Wheels" },
  { value: "towing", label: "Towing" },
  { value: "transportation_rideshare", label: "Transportation / Rideshare" },
  { value: "tutoring", label: "Tutoring" },
  { value: "urgent_care", label: "Urgent Care / Clinic" },
  { value: "veterinary", label: "Veterinary" },
  { value: "videographer", label: "Videographer" },
  { value: "web_design_it", label: "Web Design / IT Services" },
  { value: "wedding_services", label: "Wedding Services" },
  { value: "yoga_pilates", label: "Yoga / Pilates" },
] as const;

export const RELIGIOUS_INDUSTRY_VALUES = [
  "church",
  "religious_services",
  "ministry",
  "community_event",
] as const;

export function isReligiousIndustry(value: string | null | undefined): boolean {
  if (!value) return false;
  return (RELIGIOUS_INDUSTRY_VALUES as readonly string[]).includes(value);
}

export const AD_PLANS = {
  image_5: { label: "Standard Image Ad", price: 24, seconds: 7 },
  slider_10: { label: "Featured Slider Ad", price: 48, seconds: 10 },
} as const;

export type AdPlan = keyof typeof AD_PLANS;
