/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlaceholderRouteImport } from './routes/placeholder'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as EditAdRouteImport } from './routes/edit-ad'
import { Route as DesignRouteImport } from './routes/design'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AllianceRouteImport } from './routes/alliance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as CityRouteImport } from './routes/$city'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SdcountyIndexRouteImport } from './routes/sdcounty.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CityIndexRouteImport } from './routes/$city.index'
import { Route as TermsMembershipRouteImport } from './routes/terms.membership'
import { Route as TermsAiAuditRouteImport } from './routes/terms.ai-audit'
import { Route as SdcountySlugRouteImport } from './routes/sdcounty.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DesignReturnRouteImport } from './routes/design.return'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdAdNumberRouteImport } from './routes/ad.$adNumber'
import { Route as ActivateArtworkRouteImport } from './routes/activate_.artwork'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as CityActivateRouteImport } from './routes/$city.activate'
import { Route as CitySlugRouteImport } from './routes/$city.$slug'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as CityAdAdNumberRouteImport } from './routes/$city.ad.$adNumber'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicDirectoryRefreshRouteImport } from './routes/api/public/directory/refresh'
import { Route as ApiPublicDirectoryAnswersDotjsonRouteImport } from './routes/api/public/directory/answers[.]json'
import { Route as ApiPublicDirectoryCategoryRouteImport } from './routes/api/public/directory/$category'
import { Route as ApiPublicCampaignsResendWebhookRouteImport } from './routes/api/public/campaigns/resend-webhook'
import { Route as ApiPublicAdImageAdNumberRouteImport } from './routes/api/public/ad-image.$adNumber'
import { Route as ApiPublicDirectoryCategorySlugRouteImport } from './routes/api/public/directory/$category.$slug'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceholderRoute = PlaceholderRouteImport.update({
  id: '/placeholder',
  path: '/placeholder',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const EditAdRoute = EditAdRouteImport.update({
  id: '/edit-ad',
  path: '/edit-ad',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AllianceRoute = AllianceRouteImport.update({
  id: '/alliance',
  path: '/alliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SdcountyIndexRoute = SdcountyIndexRouteImport.update({
  id: '/sdcounty/',
  path: '/sdcounty/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CityIndexRoute = CityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CityRoute,
} as any)
const TermsMembershipRoute = TermsMembershipRouteImport.update({
  id: '/terms/membership',
  path: '/terms/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAiAuditRoute = TermsAiAuditRouteImport.update({
  id: '/terms/ai-audit',
  path: '/terms/ai-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SdcountySlugRoute = SdcountySlugRouteImport.update({
  id: '/sdcounty/$slug',
  path: '/sdcounty/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignReturnRoute = DesignReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => DesignRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdAdNumberRoute = AdAdNumberRouteImport.update({
  id: '/ad/$adNumber',
  path: '/ad/$adNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateArtworkRoute = ActivateArtworkRouteImport.update({
  id: '/activate_/artwork',
  path: '/activate/artwork',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const CityActivateRoute = CityActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => CityRoute,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CityRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const CityAdAdNumberRoute = CityAdAdNumberRouteImport.update({
  id: '/ad/$adNumber',
  path: '/ad/$adNumber',
  getParentRoute: () => CityRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDirectoryRefreshRoute =
  ApiPublicDirectoryRefreshRouteImport.update({
    id: '/api/public/directory/refresh',
    path: '/api/public/directory/refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDirectoryAnswersDotjsonRoute =
  ApiPublicDirectoryAnswersDotjsonRouteImport.update({
    id: '/api/public/directory/answers.json',
    path: '/api/public/directory/answers.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDirectoryCategoryRoute =
  ApiPublicDirectoryCategoryRouteImport.update({
    id: '/api/public/directory/$category',
    path: '/api/public/directory/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCampaignsResendWebhookRoute =
  ApiPublicCampaignsResendWebhookRouteImport.update({
    id: '/api/public/campaigns/resend-webhook',
    path: '/api/public/campaigns/resend-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdImageAdNumberRoute =
  ApiPublicAdImageAdNumberRouteImport.update({
    id: '/api/public/ad-image/$adNumber',
    path: '/api/public/ad-image/$adNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDirectoryCategorySlugRoute =
  ApiPublicDirectoryCategorySlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ApiPublicDirectoryCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$city': typeof CityRouteWithChildren
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRouteWithChildren
  '/alliance': typeof AllianceRoute
  '/auth': typeof AuthRoute
  '/design': typeof DesignRouteWithChildren
  '/edit-ad': typeof EditAdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/placeholder': typeof PlaceholderRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/$city/$slug': typeof CitySlugRoute
  '/$city/activate': typeof CityActivateRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activate/artwork': typeof ActivateArtworkRoute
  '/ad/$adNumber': typeof AdAdNumberRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/design/return': typeof DesignReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/sdcounty/$slug': typeof SdcountySlugRoute
  '/terms/ai-audit': typeof TermsAiAuditRoute
  '/terms/membership': typeof TermsMembershipRoute
  '/$city/': typeof CityIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/sdcounty/': typeof SdcountyIndexRoute
  '/$city/ad/$adNumber': typeof CityAdAdNumberRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/ad-image/$adNumber': typeof ApiPublicAdImageAdNumberRoute
  '/api/public/campaigns/resend-webhook': typeof ApiPublicCampaignsResendWebhookRoute
  '/api/public/directory/$category': typeof ApiPublicDirectoryCategoryRouteWithChildren
  '/api/public/directory/answers.json': typeof ApiPublicDirectoryAnswersDotjsonRoute
  '/api/public/directory/refresh': typeof ApiPublicDirectoryRefreshRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/directory/$category/$slug': typeof ApiPublicDirectoryCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/alliance': typeof AllianceRoute
  '/auth': typeof AuthRoute
  '/design': typeof DesignRouteWithChildren
  '/edit-ad': typeof EditAdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/placeholder': typeof PlaceholderRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/$city/$slug': typeof CitySlugRoute
  '/$city/activate': typeof CityActivateRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activate/artwork': typeof ActivateArtworkRoute
  '/ad/$adNumber': typeof AdAdNumberRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/design/return': typeof DesignReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/sdcounty/$slug': typeof SdcountySlugRoute
  '/terms/ai-audit': typeof TermsAiAuditRoute
  '/terms/membership': typeof TermsMembershipRoute
  '/$city': typeof CityIndexRoute
  '/admin': typeof AdminIndexRoute
  '/sdcounty': typeof SdcountyIndexRoute
  '/$city/ad/$adNumber': typeof CityAdAdNumberRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/ad-image/$adNumber': typeof ApiPublicAdImageAdNumberRoute
  '/api/public/campaigns/resend-webhook': typeof ApiPublicCampaignsResendWebhookRoute
  '/api/public/directory/$category': typeof ApiPublicDirectoryCategoryRouteWithChildren
  '/api/public/directory/answers.json': typeof ApiPublicDirectoryAnswersDotjsonRoute
  '/api/public/directory/refresh': typeof ApiPublicDirectoryRefreshRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/directory/$category/$slug': typeof ApiPublicDirectoryCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$city': typeof CityRouteWithChildren
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRouteWithChildren
  '/alliance': typeof AllianceRoute
  '/auth': typeof AuthRoute
  '/design': typeof DesignRouteWithChildren
  '/edit-ad': typeof EditAdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/placeholder': typeof PlaceholderRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/$city/$slug': typeof CitySlugRoute
  '/$city/activate': typeof CityActivateRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/activate_/artwork': typeof ActivateArtworkRoute
  '/ad/$adNumber': typeof AdAdNumberRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/design/return': typeof DesignReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/sdcounty/$slug': typeof SdcountySlugRoute
  '/terms/ai-audit': typeof TermsAiAuditRoute
  '/terms/membership': typeof TermsMembershipRoute
  '/$city/': typeof CityIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/sdcounty/': typeof SdcountyIndexRoute
  '/$city/ad/$adNumber': typeof CityAdAdNumberRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/ad-image/$adNumber': typeof ApiPublicAdImageAdNumberRoute
  '/api/public/campaigns/resend-webhook': typeof ApiPublicCampaignsResendWebhookRoute
  '/api/public/directory/$category': typeof ApiPublicDirectoryCategoryRouteWithChildren
  '/api/public/directory/answers.json': typeof ApiPublicDirectoryAnswersDotjsonRoute
  '/api/public/directory/refresh': typeof ApiPublicDirectoryRefreshRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/directory/$category/$slug': typeof ApiPublicDirectoryCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$city'
    | '/activate'
    | '/admin'
    | '/alliance'
    | '/auth'
    | '/design'
    | '/edit-ad'
    | '/llms.txt'
    | '/mcp'
    | '/placeholder'
    | '/pricing'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/submit'
    | '/unsubscribe'
    | '/$city/$slug'
    | '/$city/activate'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/activate/artwork'
    | '/ad/$adNumber'
    | '/admin/campaigns'
    | '/admin/disputes'
    | '/checkout/return'
    | '/design/return'
    | '/email/unsubscribe'
    | '/sdcounty/$slug'
    | '/terms/ai-audit'
    | '/terms/membership'
    | '/$city/'
    | '/admin/'
    | '/sdcounty/'
    | '/$city/ad/$adNumber'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/suppression'
    | '/api/public/ad-image/$adNumber'
    | '/api/public/campaigns/resend-webhook'
    | '/api/public/directory/$category'
    | '/api/public/directory/answers.json'
    | '/api/public/directory/refresh'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/directory/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/alliance'
    | '/auth'
    | '/design'
    | '/edit-ad'
    | '/llms.txt'
    | '/mcp'
    | '/placeholder'
    | '/pricing'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/submit'
    | '/unsubscribe'
    | '/$city/$slug'
    | '/$city/activate'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/activate/artwork'
    | '/ad/$adNumber'
    | '/admin/campaigns'
    | '/admin/disputes'
    | '/checkout/return'
    | '/design/return'
    | '/email/unsubscribe'
    | '/sdcounty/$slug'
    | '/terms/ai-audit'
    | '/terms/membership'
    | '/$city'
    | '/admin'
    | '/sdcounty'
    | '/$city/ad/$adNumber'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/suppression'
    | '/api/public/ad-image/$adNumber'
    | '/api/public/campaigns/resend-webhook'
    | '/api/public/directory/$category'
    | '/api/public/directory/answers.json'
    | '/api/public/directory/refresh'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/directory/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/$city'
    | '/activate'
    | '/admin'
    | '/alliance'
    | '/auth'
    | '/design'
    | '/edit-ad'
    | '/llms.txt'
    | '/mcp'
    | '/placeholder'
    | '/pricing'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/submit'
    | '/unsubscribe'
    | '/$city/$slug'
    | '/$city/activate'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/activate_/artwork'
    | '/ad/$adNumber'
    | '/admin/campaigns'
    | '/admin/disputes'
    | '/checkout/return'
    | '/design/return'
    | '/email/unsubscribe'
    | '/sdcounty/$slug'
    | '/terms/ai-audit'
    | '/terms/membership'
    | '/$city/'
    | '/admin/'
    | '/sdcounty/'
    | '/$city/ad/$adNumber'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/suppression'
    | '/api/public/ad-image/$adNumber'
    | '/api/public/campaigns/resend-webhook'
    | '/api/public/directory/$category'
    | '/api/public/directory/answers.json'
    | '/api/public/directory/refresh'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/directory/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityRoute: typeof CityRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  AdminRoute: typeof AdminRouteWithChildren
  AllianceRoute: typeof AllianceRoute
  AuthRoute: typeof AuthRoute
  DesignRoute: typeof DesignRouteWithChildren
  EditAdRoute: typeof EditAdRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  PlaceholderRoute: typeof PlaceholderRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ActivateArtworkRoute: typeof ActivateArtworkRoute
  AdAdNumberRoute: typeof AdAdNumberRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  SdcountySlugRoute: typeof SdcountySlugRoute
  TermsAiAuditRoute: typeof TermsAiAuditRoute
  TermsMembershipRoute: typeof TermsMembershipRoute
  SdcountyIndexRoute: typeof SdcountyIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicAdImageAdNumberRoute: typeof ApiPublicAdImageAdNumberRoute
  ApiPublicCampaignsResendWebhookRoute: typeof ApiPublicCampaignsResendWebhookRoute
  ApiPublicDirectoryCategoryRoute: typeof ApiPublicDirectoryCategoryRouteWithChildren
  ApiPublicDirectoryAnswersDotjsonRoute: typeof ApiPublicDirectoryAnswersDotjsonRoute
  ApiPublicDirectoryRefreshRoute: typeof ApiPublicDirectoryRefreshRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placeholder': {
      id: '/placeholder'
      path: '/placeholder'
      fullPath: '/placeholder'
      preLoaderRoute: typeof PlaceholderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-ad': {
      id: '/edit-ad'
      path: '/edit-ad'
      fullPath: '/edit-ad'
      preLoaderRoute: typeof EditAdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alliance': {
      id: '/alliance'
      path: '/alliance'
      fullPath: '/alliance'
      preLoaderRoute: typeof AllianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city': {
      id: '/$city'
      path: '/$city'
      fullPath: '/$city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdcounty/': {
      id: '/sdcounty/'
      path: '/sdcounty'
      fullPath: '/sdcounty/'
      preLoaderRoute: typeof SdcountyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$city/': {
      id: '/$city/'
      path: '/'
      fullPath: '/$city/'
      preLoaderRoute: typeof CityIndexRouteImport
      parentRoute: typeof CityRoute
    }
    '/terms/membership': {
      id: '/terms/membership'
      path: '/terms/membership'
      fullPath: '/terms/membership'
      preLoaderRoute: typeof TermsMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/ai-audit': {
      id: '/terms/ai-audit'
      path: '/terms/ai-audit'
      fullPath: '/terms/ai-audit'
      preLoaderRoute: typeof TermsAiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdcounty/$slug': {
      id: '/sdcounty/$slug'
      path: '/sdcounty/$slug'
      fullPath: '/sdcounty/$slug'
      preLoaderRoute: typeof SdcountySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/return': {
      id: '/design/return'
      path: '/return'
      fullPath: '/design/return'
      preLoaderRoute: typeof DesignReturnRouteImport
      parentRoute: typeof DesignRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ad/$adNumber': {
      id: '/ad/$adNumber'
      path: '/ad/$adNumber'
      fullPath: '/ad/$adNumber'
      preLoaderRoute: typeof AdAdNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate_/artwork': {
      id: '/activate_/artwork'
      path: '/activate/artwork'
      fullPath: '/activate/artwork'
      preLoaderRoute: typeof ActivateArtworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city/activate': {
      id: '/$city/activate'
      path: '/activate'
      fullPath: '/$city/activate'
      preLoaderRoute: typeof CityActivateRouteImport
      parentRoute: typeof CityRoute
    }
    '/$city/$slug': {
      id: '/$city/$slug'
      path: '/$slug'
      fullPath: '/$city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof CityRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city/ad/$adNumber': {
      id: '/$city/ad/$adNumber'
      path: '/ad/$adNumber'
      fullPath: '/$city/ad/$adNumber'
      preLoaderRoute: typeof CityAdAdNumberRouteImport
      parentRoute: typeof CityRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/directory/refresh': {
      id: '/api/public/directory/refresh'
      path: '/api/public/directory/refresh'
      fullPath: '/api/public/directory/refresh'
      preLoaderRoute: typeof ApiPublicDirectoryRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/directory/answers.json': {
      id: '/api/public/directory/answers.json'
      path: '/api/public/directory/answers.json'
      fullPath: '/api/public/directory/answers.json'
      preLoaderRoute: typeof ApiPublicDirectoryAnswersDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/directory/$category': {
      id: '/api/public/directory/$category'
      path: '/api/public/directory/$category'
      fullPath: '/api/public/directory/$category'
      preLoaderRoute: typeof ApiPublicDirectoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/campaigns/resend-webhook': {
      id: '/api/public/campaigns/resend-webhook'
      path: '/api/public/campaigns/resend-webhook'
      fullPath: '/api/public/campaigns/resend-webhook'
      preLoaderRoute: typeof ApiPublicCampaignsResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ad-image/$adNumber': {
      id: '/api/public/ad-image/$adNumber'
      path: '/api/public/ad-image/$adNumber'
      fullPath: '/api/public/ad-image/$adNumber'
      preLoaderRoute: typeof ApiPublicAdImageAdNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/directory/$category/$slug': {
      id: '/api/public/directory/$category/$slug'
      path: '/$slug'
      fullPath: '/api/public/directory/$category/$slug'
      preLoaderRoute: typeof ApiPublicDirectoryCategorySlugRouteImport
      parentRoute: typeof ApiPublicDirectoryCategoryRoute
    }
  }
}

interface CityRouteChildren {
  CitySlugRoute: typeof CitySlugRoute
  CityActivateRoute: typeof CityActivateRoute
  CityIndexRoute: typeof CityIndexRoute
  CityAdAdNumberRoute: typeof CityAdAdNumberRoute
}

const CityRouteChildren: CityRouteChildren = {
  CitySlugRoute: CitySlugRoute,
  CityActivateRoute: CityActivateRoute,
  CityIndexRoute: CityIndexRoute,
  CityAdAdNumberRoute: CityAdAdNumberRoute,
}

const CityRouteWithChildren = CityRoute._addFileChildren(CityRouteChildren)

interface AdminRouteChildren {
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DesignRouteChildren {
  DesignReturnRoute: typeof DesignReturnRoute
}

const DesignRouteChildren: DesignRouteChildren = {
  DesignReturnRoute: DesignReturnRoute,
}

const DesignRouteWithChildren =
  DesignRoute._addFileChildren(DesignRouteChildren)

interface ApiPublicDirectoryCategoryRouteChildren {
  ApiPublicDirectoryCategorySlugRoute: typeof ApiPublicDirectoryCategorySlugRoute
}

const ApiPublicDirectoryCategoryRouteChildren: ApiPublicDirectoryCategoryRouteChildren =
  {
    ApiPublicDirectoryCategorySlugRoute: ApiPublicDirectoryCategorySlugRoute,
  }

const ApiPublicDirectoryCategoryRouteWithChildren =
  ApiPublicDirectoryCategoryRoute._addFileChildren(
    ApiPublicDirectoryCategoryRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityRoute: CityRouteWithChildren,
  ActivateRoute: ActivateRoute,
  AdminRoute: AdminRouteWithChildren,
  AllianceRoute: AllianceRoute,
  AuthRoute: AuthRoute,
  DesignRoute: DesignRouteWithChildren,
  EditAdRoute: EditAdRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  PlaceholderRoute: PlaceholderRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ActivateArtworkRoute: ActivateArtworkRoute,
  AdAdNumberRoute: AdAdNumberRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  SdcountySlugRoute: SdcountySlugRoute,
  TermsAiAuditRoute: TermsAiAuditRoute,
  TermsMembershipRoute: TermsMembershipRoute,
  SdcountyIndexRoute: SdcountyIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicAdImageAdNumberRoute: ApiPublicAdImageAdNumberRoute,
  ApiPublicCampaignsResendWebhookRoute: ApiPublicCampaignsResendWebhookRoute,
  ApiPublicDirectoryCategoryRoute: ApiPublicDirectoryCategoryRouteWithChildren,
  ApiPublicDirectoryAnswersDotjsonRoute: ApiPublicDirectoryAnswersDotjsonRoute,
  ApiPublicDirectoryRefreshRoute: ApiPublicDirectoryRefreshRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
